version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: shareitDb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  gateway:
    build: ./gateway
    image: shareit-gateway-image
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
    - server
    - db
    environment:
    - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: shareit-server-image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shareitDb:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


